### PR TITLE
Support ghc-9.6 and ghc-9.8

### PR DESCRIPTION
**Pull request by erikd**
Builds locally.

### CODE REVIEW

**Comment by michaelpj** [comment]
We need the `th-abstraction` bound bumped too. It builds fine with `th-abstraction-0.5`.

**Comment by erikd** [comment]
Done!

**Comment by erikd** [comment]
Ping?

**Comment by andreasabel** [comment]
ATTN: @ryantrinkle

**Comment by andreasabel** [comment]
I met @ryantrinkle at MuniHac yesterday and brought this to his attention...
He might not read all of his notifications (that's what he told me), so one could try other channels (e.g. email).

**Comment by endgame** [comment]
I'm not a maintainer here, but do you reckon you could steal the CI fixes from #19 and see if it all still works? Then I'll see if I can get a hold of Ryan.

**Comment by erikd** [comment]
I am already using the commit at https://github.com/mokus0/th-extras/pull/21 as an SRP in my `cabal.project`.

**Comment by andreasabel** [comment]
I sent an email to @ryantrinkle about this.

**Comment by ryantrinkle** [comment]
@erikd, @endgame, @andreasabel I'd be happy to make any of you guys maintainers if you are interested.

**Comment by andreasabel** [comment]
I am not a user of this package, so I step back. @erikd, maybe you can help out here?

**Comment by erikd** [comment]
Yes, happy to be a maintainer.

**Comment by erikd** [comment]
Still needs a hackage release. I am also happy to become a hackage co-maintainer (user name ErikDeCastroLopo).

**Comment by ysangkok** [comment]
@erikd You're a maintainer now, see [hackage](https://hackage.haskell.org/package/th-extras/maintainers/). Would it be possible to make a release? That would address

* https://github.com/commercialhaskell/stackage/issues/7074

**Comment by erikd** [comment]
@ysangkok  New version uploaded to Hackage. Thanks!

**Pull request merged**
