### PR TITLE
Support GHC 9.2

### PR DESCRIPTION
**Pull request by Bodigrim**
@ryantrinkle would it be possible to have a Hackage release for this please?

### CODE REVIEW

**Comment by pepeiborra** [comment]
+1

**Comment by arbitrary-dev** [comment]
Closes #15

**Review by Ericson2314 — APPROVED** [review]

**Comment by Ericson2314** [comment]
@Bodigrim can you add a change log entry?

**Comment by Bodigrim** [comment]
@Ericson2314 I cannot, this package has no pre-existing changelog.

**Comment by Ericson2314** [comment]
Fair enough, we'll fix that.

**Comment by Ericson2314** [comment]
Have change log, tag, etc. now. It wouldn't let me push to your PR as I don't have perms, so I opened a new one: https://github.com/mokus0/th-extras/pull/17

**Comment by Ericson2314** [comment]
This one can be closed.

**Comment by Ericson2314** [comment]
Thanks again, @Bodigrim.

**Pull request merged**
